# Generated by Django 4.1.6 on 2023-02-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Use',
            new_name='conversations',
        ),
    ]
