# Generated by Django 4.1.6 on 2023-02-16 20:08

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_conversations_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='audio_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])]),
            preserve_default=False,
        ),
    ]
