# Generated by Django 4.1.6 on 2023-02-17 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_conversations_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversations',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='conversations',
            name='audio_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000),
            preserve_default=False,
        ),
    ]
